import { Product } from "../types/models";

export const MOCK_PRODUCTS: Product[] = [
    {
        id: '1',
        name: 'Fresh Whole Milk',
        brand: 'Dairy Farm',
        description: '1L of pure, farm-fresh whole milk. Rich in calcium and nutrients.',
        price: 45,
        categoryId: 'dairy',
        images: ['https://img.freepik.com/free-photo/milk-bottle-isolated_1203-2415.jpg'],
        isAvailable: true,
    },
    {
        id: '2',
        name: 'Chocolate Chip Cookies',
        brand: 'Bakey',
        description: 'Crunchy cookies with premium dark chocolate chips.',
        price: 120,
        categoryId: 'snacks',
        images: ['https://img.freepik.com/free-photo/cookies-isolated-white-background_1203-1629.jpg'],
        isAvailable: true,
    },
    {
        id: '3',
        name: 'Basmati Rice',
        brand: 'India Gate',
        description: '5kg pack of long-grain aromatic basmati rice.',
        price: 850,
        categoryId: 'grains',
        images: ['https://img.freepik.com/free-photo/rice-burlap-sack-isolated-white-background_1203-2454.jpg'],
        isAvailable: true,
    },
    {
        id: '4',
        name: 'Laundry Detergent',
        brand: 'Cleanex',
        description: 'Powerful stain removal with a fresh scent. 2kg pack.',
        price: 450,
        categoryId: 'household',
        images: ['https://img.freepik.com/free-photo/laundry-detergent-bottle-isolated_1203-2426.jpg'],
        isAvailable: true,
    },
    {
        id: '5',
        name: 'Premium Ballpoint Pens',
        brand: 'OfficePlus',
        description: 'Set of 5 smooth-writing blue ink pens.',
        price: 50,
        categoryId: 'stationery',
        images: ['https://img.freepik.com/free-photo/pen-isolated-white-background_1203-2334.jpg'],
        isAvailable: false,
    },
    {
        id: '6',
        name: 'Organic Red Apples',
        brand: 'NatureFresh',
        description: 'Sweet and crunchy organic apples, 1kg.',
        price: 180,
        categoryId: 'produce',
        images: ['https://img.freepik.com/free-photo/red-apple-isolated-white-background_1203-2418.jpg'],
        isAvailable: true,
    },
];
